// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Infrastructure.Persistence;

#nullable disable

namespace WebApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716085823_AddExpenseEntries")]
    partial class AddExpenseEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Domain.ExpenseEntries.ExpenseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ExpenseReportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ReportMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ReportYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("ExpenseReportId");

                    b.HasIndex("ExpenseReportId", "IsDeleted");

                    b.HasIndex("ExpenseReportId", "IsDeleted", "ExpenseDate");

                    b.HasIndex("ExpenseReportId", "ReportYear", "ReportMonth");

                    b.ToTable("expense_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_expense_entries_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_expense_entries_currency_eur", "\"Currency\" = 'EUR'");

                            t.HasCheckConstraint(
                                "CK_expense_entries_expense_date_report_month",
                                "EXTRACT(YEAR FROM \"ExpenseDate\") = \"ReportYear\" " +
                                "AND EXTRACT(MONTH FROM \"ExpenseDate\") = \"ReportMonth\"");

                            t.HasCheckConstraint("CK_expense_entries_report_month_valid", "\"ReportMonth\" BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("WebApi.Domain.ExpenseReports.ExpenseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedUserFullName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Year", "Month");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("expense_reports", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MonthlyExpenseQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("MonthlyExpenseQuota");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.ExpenseEntries.ExpenseEntry", b =>
                {
                    b.HasOne("WebApi.Domain.ExpenseReports.ExpenseReport", null)
                        .WithMany()
                        .HasForeignKey("ExpenseReportId", "ReportYear", "ReportMonth")
                        .HasPrincipalKey("Id", "Year", "Month")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_expense_entries_expense_reports_period");

                    b.OwnsOne("WebApi.Domain.ExpenseEntries.BillingAddress", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("ExpenseEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("BillingCity");

                            b1.Property<string>("MerchantName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("BillingMerchantName");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("BillingPostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("BillingStreet");

                            b1.HasKey("ExpenseEntryId");

                            b1.ToTable("expense_entries");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseEntryId");
                        });

                    b.OwnsOne("WebApi.Domain.ExpenseEntries.ExpenseDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("ExpenseEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Description");

                            b1.HasKey("ExpenseEntryId");

                            b1.ToTable("expense_entries");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseEntryId");
                        });

                    b.OwnsOne("WebApi.Domain.ExpenseEntries.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("ExpenseEntryId");

                            b1.ToTable("expense_entries");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseEntryId");

                            b1.OwnsOne("WebApi.Domain.ExpenseEntries.Currency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("MoneyExpenseEntryId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("MoneyExpenseEntryId");

                                    b2.ToTable("expense_entries");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyExpenseEntryId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Domain.ExpenseReports.ExpenseReport", b =>
                {
                    b.HasOne("WebApi.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Domain.Users.User", b =>
                {
                    b.OwnsOne("WebApi.Domain.Users.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.HasIndex("LastName", "FirstName");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("WebApi.Domain.Users.PostalAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Street");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
